In [1]:
import torch
import pickle

with open( "x_train_hist.p", "rb" ) as file:
    x_train_hist = pickle.load(file)
    
with open( "y_train_hist.p", "rb" ) as file:
    y_train_hist = pickle.load(file)
    
with open( "x_valid_hist.p", "rb" ) as file:
    x_valid_hist = pickle.load(file)
    
with open( "y_valid_hist.p", "rb" ) as file:
    y_valid_hist = pickle.load(file)

In [2]:
import torch
import random
import numpy as np
import torch.optim as optim
from torch.utils.data import DataLoader
from torch.nn import CrossEntropyLoss
from tqdm.auto import tqdm

from mriqa_dataset import MRIQADataset
from networks import ClassicCNN, PhilsClassicCnn, CatNet

If you use TorchIO for your research, please cite the following paper:
Pérez-García et al., TorchIO: a Python library for efficient loading,
preprocessing, augmentation and patch-based sampling of medical images
in deep learning. Link: https://arxiv.org/abs/2003.04696



In [3]:
import torch_optimizer as optim
num_epochs = len(x_train_hist)

net = CatNet(num_classes=5)
net = net.cuda()

#optimizer = optim.Adam(net.parameters())
optimizer = optim.Ranger(
    net.parameters(),
    lr=9e-4,
    alpha=0.5,
    k=6,
    N_sma_threshhold=5,
    betas=(.95, 0.999),
    eps=1e-5,
    weight_decay=0
)

flat_lr = round(num_epochs * 0.7)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=(num_epochs-flat_lr))
#lmbda = lambda epoch: 0.95
#scheduler = torch.optim.lr_scheduler.MultiplicativeLR(optimizer, lr_lambda=lmbda)
ce = CrossEntropyLoss().cuda()

def get_lr(optimizer):
    for param_group in optimizer.param_groups:
        return param_group['lr']



print(f"I will do flat Learning rate for {flat_lr} epochs and then do {num_epochs-flat_lr} epochs cosine annealing")

I will do flat Learning rate for 217 epochs and then do 93 epochs cosine annealing


In [4]:
best_val_loss = 999

loss_csv = open('losses.csv', 'w')
loss_csv.write('epoch,training,validation\n')
num_mini_batches = 13
    
print("start training")
for epoch in range(num_epochs):
    epoch_loss = 0.0
    net.train()
    
    train_batches = x_train_hist[epoch]
    train_labels = y_train_hist[epoch]

    # train loop
    for sample, label in tqdm(zip(train_batches, train_labels), total=len(train_batches), leave=False):       
        sample = sample.cuda()
        label = label.cuda()

        prediction = net(sample)
        loss = ce(prediction, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(net.parameters(), 1)
        optimizer.step()
        epoch_loss += loss.item()
    
    # do annealing after 70% of the training time
    if epoch > flat_lr:
        scheduler.step()

    print('[{}] train-loss: {}'.format(epoch, epoch_loss / num_mini_batches))
    loss_csv.write(str(epoch) + ',' + str(epoch_loss / num_mini_batches))
    loss_csv.flush()

    # validation loop
    net.eval()
    mean_validation_loss = 0
    num_validation_mini_batches = 11
    
    if epoch % 3 == 0:
        valid_batches = x_valid_hist[epoch//5]
        valid_labels = y_valid_hist[epoch//5]
        with torch.no_grad():
            for sample, label in tqdm(zip(valid_batches, valid_labels), total=len(valid_batches), leave=False):              
                sample = sample.cuda()
                label = label.cuda()

                prediction = net(sample)
                validation_loss = ce(prediction, label)

                mean_validation_loss += validation_loss.item()
            print(f'[{epoch}] validation-loss: {mean_validation_loss / num_validation_mini_batches} Lerning Rate {get_lr(optimizer)}')
            loss_csv.write(',' + str(mean_validation_loss / num_validation_mini_batches) + '\n')
            loss_csv.flush()

        # save best model
        if mean_validation_loss <= best_val_loss:
            torch.save({'epoch': epoch,
                        'model_state_dict': net.state_dict(),
                        'optimizer_state_dict': optimizer.state_dict(),
                        'loss': validation_loss.item()}, 'checkpoint_best')
            best_val_loss = mean_validation_loss

print('DONE.')

start training


..\torch\csrc\utils\python_arg_parser.cpp:756: UserWarning: This overload of addcmul_ is deprecated:
	addcmul_(Number value, Tensor tensor1, Tensor tensor2)
Consider using one of the following signatures instead:
	addcmul_(Tensor tensor1, Tensor tensor2, *, Number value)


[0] train-loss: 0.49916683710538423


[0] validation-loss: 0.43635866858742456 Lerning Rate 0.0009


[1] train-loss: 0.5042969080118033


[2] train-loss: 0.502527851324815


[3] train-loss: 0.49011211211864764


[3] validation-loss: 0.4354281642220237 Lerning Rate 0.0009


[4] train-loss: 0.4894049626130324


[5] train-loss: 0.4703590044608483


[6] train-loss: 0.4594911520297711


[6] validation-loss: 0.4453528035770763 Lerning Rate 0.0009


[7] train-loss: 0.46967409207270694


[8] train-loss: 0.4401281705269447


[9] train-loss: 0.4788716664681068


[9] validation-loss: 0.4659023935144598 Lerning Rate 0.0009


[10] train-loss: 0.41562962532043457


[11] train-loss: 0.4464631997621976


[12] train-loss: 0.43993000800792986


[12] validation-loss: 0.4266378012570468 Lerning Rate 0.0009


[13] train-loss: 0.470884607388423


[14] train-loss: 0.4073796639075646


[15] train-loss: 0.4105930970265315


[15] validation-loss: 0.3861066861586137 Lerning Rate 0.0009


[16] train-loss: 0.40913432378035325


[17] train-loss: 0.4116976811335637


[18] train-loss: 0.4236655326989981


[18] validation-loss: 0.34754781289534137 Lerning Rate 0.0009


[19] train-loss: 0.42576966835902286


[20] train-loss: 0.38862869372734654


[21] train-loss: 0.40481441754561204


[21] validation-loss: 0.35848441990939056 Lerning Rate 0.0009


[22] train-loss: 0.41857856053572434


[23] train-loss: 0.39249067123119646


[24] train-loss: 0.3916969574414767


[24] validation-loss: 0.33690397305922076 Lerning Rate 0.0009


[25] train-loss: 0.3837587099808913


[26] train-loss: 0.38879701724419224


[27] train-loss: 0.3746478282488309


[27] validation-loss: 0.34350822188637475 Lerning Rate 0.0009


[28] train-loss: 0.3741900370671199


[29] train-loss: 0.40846112141242397


[30] train-loss: 0.36036332753988415


[30] validation-loss: 0.32118126479062165 Lerning Rate 0.0009


[31] train-loss: 0.3762082503392146


[32] train-loss: 0.36641988387474644


[33] train-loss: 0.3324785049145038


[33] validation-loss: 0.31186134164983575 Lerning Rate 0.0009


[34] train-loss: 0.35815569987663853


[35] train-loss: 0.3632758122224074


[36] train-loss: 0.32744239843808687


[36] validation-loss: 0.3447266600348733 Lerning Rate 0.0009


[37] train-loss: 0.32603997450608474


[38] train-loss: 0.33413854929117054


[39] train-loss: 0.3163247246008653


[39] validation-loss: 0.30219819329001685 Lerning Rate 0.0009


[40] train-loss: 0.3254401317009559


[41] train-loss: 0.31918196494762713


[42] train-loss: 0.37064001193413365


[42] validation-loss: 0.3085981932553378 Lerning Rate 0.0009


[43] train-loss: 0.33168972455538237


[44] train-loss: 0.32873876278217024


[45] train-loss: 0.32709018083719105


[45] validation-loss: 0.31720795414664527 Lerning Rate 0.0009


[46] train-loss: 0.3144616622191209


[47] train-loss: 0.35395089938090396


[48] train-loss: 0.3299949077459482


[48] validation-loss: 0.2996195771477439 Lerning Rate 0.0009


[49] train-loss: 0.3230504531126756


[50] train-loss: 0.31540873417487514


[51] train-loss: 0.31526952523451585


[51] validation-loss: 0.29608034003864636 Lerning Rate 0.0009


[52] train-loss: 0.31543976068496704


[53] train-loss: 0.32322662610274094


[54] train-loss: 0.3014892477255601


[54] validation-loss: 0.30930680578405206 Lerning Rate 0.0009


[55] train-loss: 0.3341328455851628


[56] train-loss: 0.332170491035168


[57] train-loss: 0.2936213337458097


[57] validation-loss: 0.34855798157778656 Lerning Rate 0.0009


[58] train-loss: 0.32551870896266055


[59] train-loss: 0.301493016573099


[60] train-loss: 0.31627015425608707


[60] validation-loss: 0.29563313180750067 Lerning Rate 0.0009


[61] train-loss: 0.32457224222329945


[62] train-loss: 0.33328341520749605


[63] train-loss: 0.29879181660138643


[63] validation-loss: 0.3059271357276223 Lerning Rate 0.0009


[64] train-loss: 0.32299867043128383


[65] train-loss: 0.32037102717619675


[66] train-loss: 0.29560611798213077


[66] validation-loss: 0.36945805766365747 Lerning Rate 0.0009


[67] train-loss: 0.3501461102412297


[68] train-loss: 0.3010344367760878


[69] train-loss: 0.3148274284142714


[69] validation-loss: 0.26892654462294147 Lerning Rate 0.0009


[70] train-loss: 0.30844642565800595


[71] train-loss: 0.31354783131526065


[72] train-loss: 0.3120528001051683


[72] validation-loss: 0.35635369474237616 Lerning Rate 0.0009


[73] train-loss: 0.3383937157117404


[74] train-loss: 0.3160783556791452


[75] train-loss: 0.29494993503277117


[75] validation-loss: 0.33061734112826263 Lerning Rate 0.0009


[76] train-loss: 0.30615771275300246


[77] train-loss: 0.312660093490894


[78] train-loss: 0.3415491580963135


[78] validation-loss: 0.2892673774199052 Lerning Rate 0.0009


[79] train-loss: 0.2940917656971858


[80] train-loss: 0.3221342380230243


[81] train-loss: 0.3176697355050307


[81] validation-loss: 0.33147496526891534 Lerning Rate 0.0009


[82] train-loss: 0.3082576348231389


[83] train-loss: 0.31940802244039684


[84] train-loss: 0.31426969399819005


[84] validation-loss: 0.27651014111258765 Lerning Rate 0.0009


[85] train-loss: 0.3092080492239732


[86] train-loss: 0.31339472990769607


[87] train-loss: 0.3408208718666664


[87] validation-loss: 0.3071114258332686 Lerning Rate 0.0009


[88] train-loss: 0.3114491609426645


[89] train-loss: 0.32675135135650635


[90] train-loss: 0.3222773762849661


[90] validation-loss: 0.2688968506726352 Lerning Rate 0.0009


[91] train-loss: 0.3153402897027823


[92] train-loss: 0.2874324000798739


[93] train-loss: 0.32406485080718994


[93] validation-loss: 0.3493157083337957 Lerning Rate 0.0009


[94] train-loss: 0.31860289665368885


[95] train-loss: 0.30930669949604916


[96] train-loss: 0.2955138454070458


[96] validation-loss: 0.2694063295017589 Lerning Rate 0.0009


[97] train-loss: 0.30423314296282256


[98] train-loss: 0.30714727823550886


[99] train-loss: 0.30335070995184094


[99] validation-loss: 0.2864048751917752 Lerning Rate 0.0009


[100] train-loss: 0.30884966941980213


[101] train-loss: 0.29455482959747314


[102] train-loss: 0.31493149353907657


[102] validation-loss: 0.2763637900352478 Lerning Rate 0.0009


[103] train-loss: 0.3126489290824303


[104] train-loss: 0.30881510789577776


[105] train-loss: 0.2991935473221999


[105] validation-loss: 0.25867423144253815 Lerning Rate 0.0009


[106] train-loss: 0.32594149846297044


[107] train-loss: 0.31903865245672375


[108] train-loss: 0.3139895750926091


[108] validation-loss: 0.3955482244491577 Lerning Rate 0.0009


[109] train-loss: 0.3162131951405452


[110] train-loss: 0.3129394375360929


[111] train-loss: 0.3037064579816965


[111] validation-loss: 0.34258883649652655 Lerning Rate 0.0009


[112] train-loss: 0.3087924076960637


[113] train-loss: 0.30215129026999843


[114] train-loss: 0.3128982186317444


[114] validation-loss: 0.35693802616812964 Lerning Rate 0.0009


[115] train-loss: 0.3555680834330045


[116] train-loss: 0.32548458301104033


[117] train-loss: 0.30502288616620576


[117] validation-loss: 0.26113755052739923 Lerning Rate 0.0009


[118] train-loss: 0.3039194024526156


[119] train-loss: 0.3152375267102168


[120] train-loss: 0.346311289530534


[120] validation-loss: 0.2923421968113292 Lerning Rate 0.0009


[121] train-loss: 0.32046616535920364


[122] train-loss: 0.3111461951182439


[123] train-loss: 0.30502350055254424


[123] validation-loss: 0.3503661805933172 Lerning Rate 0.0009


[124] train-loss: 0.3016143716298617


[125] train-loss: 0.2978878984084496


[126] train-loss: 0.3146821673099811


[126] validation-loss: 0.28378289396112616 Lerning Rate 0.0009


[127] train-loss: 0.31943899393081665


[128] train-loss: 0.3167330026626587


[129] train-loss: 0.32672399282455444


[129] validation-loss: 0.3405072797428478 Lerning Rate 0.0009


[130] train-loss: 0.3221147839839642


[131] train-loss: 0.32345022605015683


[132] train-loss: 0.32837312955122727


[132] validation-loss: 0.3776499032974243 Lerning Rate 0.0009


[133] train-loss: 0.28995400208693284


[134] train-loss: 0.31305742263793945


[135] train-loss: 0.2994735057537372


[135] validation-loss: 0.37174390662800183 Lerning Rate 0.0009


[136] train-loss: 0.2898865800637465


[137] train-loss: 0.3140704585955693


[138] train-loss: 0.3414018016595107


[138] validation-loss: 0.3023890798742121 Lerning Rate 0.0009


[139] train-loss: 0.2984007459420424


[140] train-loss: 0.33249151706695557


[141] train-loss: 0.33526955201075626


[141] validation-loss: 0.2579460089856928 Lerning Rate 0.0009


[142] train-loss: 0.3408766251343947


[143] train-loss: 0.30871509588681734


[144] train-loss: 0.30197779031900257


[144] validation-loss: 0.3207788142290982 Lerning Rate 0.0009


[145] train-loss: 0.2885102996459374


[146] train-loss: 0.3241365597798274


[147] train-loss: 0.3038995357660147


[147] validation-loss: 0.3171453909440474 Lerning Rate 0.0009


[148] train-loss: 0.301070369206942


[149] train-loss: 0.2948710001431979


[150] train-loss: 0.32707683398173404


[150] validation-loss: 0.35632275451313367 Lerning Rate 0.0009


[151] train-loss: 0.29379133077768177


[152] train-loss: 0.3191033418361957


[153] train-loss: 0.29189038276672363


[153] validation-loss: 0.2921054796739058 Lerning Rate 0.0009


[154] train-loss: 0.2921450642439035


[155] train-loss: 0.3500946851877066


[156] train-loss: 0.3054706545976492


[156] validation-loss: 0.34213819287040015 Lerning Rate 0.0009


[157] train-loss: 0.31606406431931716


[158] train-loss: 0.31609919437995326


[159] train-loss: 0.3046766519546509


[159] validation-loss: 0.3606835061853582 Lerning Rate 0.0009


[160] train-loss: 0.33852439201795137


[161] train-loss: 0.3469184637069702


[162] train-loss: 0.29824226636153


[162] validation-loss: 0.29703729261051526 Lerning Rate 0.0009


[163] train-loss: 0.2933225402465233


[164] train-loss: 0.31843378910651576


[165] train-loss: 0.30042025217643153


[165] validation-loss: 0.36604767495935614 Lerning Rate 0.0009


[166] train-loss: 0.3388558534475473


[167] train-loss: 0.3358268646093515


[168] train-loss: 0.3089428956692035


[168] validation-loss: 0.3395573767748746 Lerning Rate 0.0009


[169] train-loss: 0.30189181291140044


[170] train-loss: 0.30003820474331194


[171] train-loss: 0.336382833810953


[171] validation-loss: 0.2786218090490861 Lerning Rate 0.0009


[172] train-loss: 0.296482306260329


[173] train-loss: 0.30093106398215663


[174] train-loss: 0.32129904398551357


[174] validation-loss: 0.4243858944286 Lerning Rate 0.0009


[175] train-loss: 0.29919975996017456


[176] train-loss: 0.34680174864255464


[177] train-loss: 0.33698779344558716


[177] validation-loss: 0.27981660582802514 Lerning Rate 0.0009


[178] train-loss: 0.3034809644405658


[179] train-loss: 0.2912757213299091


[180] train-loss: 0.29517079775150007


[180] validation-loss: 0.2978478886864402 Lerning Rate 0.0009


[181] train-loss: 0.2879293836080111


[182] train-loss: 0.31428150488780093


[183] train-loss: 0.31780024675222546


[183] validation-loss: 0.42082535136829724 Lerning Rate 0.0009


[184] train-loss: 0.32415918661997867


[185] train-loss: 0.3070365465604342


[186] train-loss: 0.32680498178188616


[186] validation-loss: 0.396645415912975 Lerning Rate 0.0009


[187] train-loss: 0.2935000933133639


[188] train-loss: 0.3011901103533231


[189] train-loss: 0.32601800790199864


[189] validation-loss: 0.36783991076729516 Lerning Rate 0.0009


[190] train-loss: 0.28886584593699527


[191] train-loss: 0.34337463745704067


[192] train-loss: 0.3154652898128216


[192] validation-loss: 0.36620145494287665 Lerning Rate 0.0009


[193] train-loss: 0.3179017901420593


[194] train-loss: 0.3027208172357999


[195] train-loss: 0.3213662000802847


[195] validation-loss: 0.2775180014696988 Lerning Rate 0.0009


[196] train-loss: 0.32424697509178746


[197] train-loss: 0.2885848650565514


[198] train-loss: 0.31181347828644973


[198] validation-loss: 0.3043572794307362 Lerning Rate 0.0009


[199] train-loss: 0.281401473742265


[200] train-loss: 0.2875552544227013


[201] train-loss: 0.29764520204984224


[201] validation-loss: 0.30994129180908203 Lerning Rate 0.0009


[202] train-loss: 0.2980296199138348


[203] train-loss: 0.3079675527719351


[204] train-loss: 0.3217271382992084


[204] validation-loss: 0.2822950103066184 Lerning Rate 0.0009


[205] train-loss: 0.3181366966320918


[206] train-loss: 0.3125396829385024


[207] train-loss: 0.3145298361778259


[207] validation-loss: 0.37261034141887317 Lerning Rate 0.0009


[208] train-loss: 0.3441704511642456


[209] train-loss: 0.3225138233258174


[210] train-loss: 0.29488208202215344


[210] validation-loss: 0.29186035286296497 Lerning Rate 0.0009


[211] train-loss: 0.31593127434070295


[212] train-loss: 0.3220343222984901


[213] train-loss: 0.30219903817543614


[213] validation-loss: 0.39624163237485016 Lerning Rate 0.0009


[214] train-loss: 0.29720289890582746


[215] train-loss: 0.29598080194913423


[216] train-loss: 0.28536383922283465


[216] validation-loss: 0.3867712129246105 Lerning Rate 0.0009


[217] train-loss: 0.29438483715057373


[218] train-loss: 0.3231753431833707


[219] train-loss: 0.3125157677210294


[219] validation-loss: 0.25549998066642066 Lerning Rate 0.0008989733766060318


[220] train-loss: 0.28666096467238206


[221] train-loss: 0.31021294685510487


[222] train-loss: 0.3422632400806134


[222] validation-loss: 0.31615048105066473 Lerning Rate 0.0008935964078916617


[223] train-loss: 0.3158107537489671


[224] train-loss: 0.288642576107612


[225] train-loss: 0.30715877276200515


[225] validation-loss: 0.33223006942055444 Lerning Rate 0.0008836675397504736


[226] train-loss: 0.2983368864426246


[227] train-loss: 0.2912676059282743


[228] train-loss: 0.29744547605514526


[228] validation-loss: 0.34846278754147614 Lerning Rate 0.0008692886558055009


[229] train-loss: 0.3057612409958473


[230] train-loss: 0.3285032006410452


[231] train-loss: 0.3323679337134728


[231] validation-loss: 0.2870998165824197 Lerning Rate 0.0008506073028637585


[232] train-loss: 0.29346493574289173


[233] train-loss: 0.29313435004307675


[234] train-loss: 0.300510443173922


[234] validation-loss: 0.33442715081301605 Lerning Rate 0.0008278151768863377


[235] train-loss: 0.2967744515492366


[236] train-loss: 0.30513554352980393


[237] train-loss: 0.3299296865096459


[237] validation-loss: 0.27481306141073053 Lerning Rate 0.0008011461559284415


[238] train-loss: 0.2969381809234619


[239] train-loss: 0.28917725269611066


[240] train-loss: 0.28740598605229306


[240] validation-loss: 0.3033814755353061 Lerning Rate 0.0007708739002340492


[241] train-loss: 0.30670333825624907


[242] train-loss: 0.3078686182315533


[243] train-loss: 0.3426579741331247


[243] validation-loss: 0.3016004508191889 Lerning Rate 0.0007373090441114927


[244] train-loss: 0.2939205215527461


[245] train-loss: 0.30604697649295515


[246] train-loss: 0.3299674620995155


[246] validation-loss: 0.2898300723596053 Lerning Rate 0.0007007960084050964


[247] train-loss: 0.28475894377781796


[248] train-loss: 0.2905223002800575


[249] train-loss: 0.29245434816067034


[249] validation-loss: 0.2607030922716314 Lerning Rate 0.0006617094662712402


[250] train-loss: 0.3109155847476079


[251] train-loss: 0.30292986447994524


[252] train-loss: 0.2937870759230394


[252] validation-loss: 0.37185352498834784 Lerning Rate 0.0006204504985247593


[253] train-loss: 0.3023057671693655


[254] train-loss: 0.30868467000814587


[255] train-loss: 0.33084623171732974


[255] validation-loss: 0.30325224182822486 Lerning Rate 0.000577442478007037


[256] train-loss: 0.34381941648629993


[257] train-loss: 0.2903720415555514


[258] train-loss: 0.30217755757845366


[258] validation-loss: 0.26418739557266235 Lerning Rate 0.0005331267252077353


[259] train-loss: 0.2900801209303049


[260] train-loss: 0.3035689959159264


[261] train-loss: 0.3000643986922044


[261] validation-loss: 0.2745296196504073 Lerning Rate 0.00048795797971937037


[262] train-loss: 0.29189242307956403


[263] train-loss: 0.2876467475524315


[264] train-loss: 0.3069488772979149


[264] validation-loss: 0.26643919402902777 Lerning Rate 0.000442399733993731


[265] train-loss: 0.29511202298677885


[266] train-loss: 0.28203398906267607


[267] train-loss: 0.30303258620775664


[267] validation-loss: 0.29189797423102637 Lerning Rate 0.00039691947728211923


[268] train-loss: 0.28627116405046904


[269] train-loss: 0.30444091099959153


[270] train-loss: 0.2927669286727905


[270] validation-loss: 0.2673622098836032 Lerning Rate 0.00035198389856301674


[271] train-loss: 0.3244528632897597


[272] train-loss: 0.33154059373415434


[273] train-loss: 0.314312613927401


[273] validation-loss: 0.2946392731233077 Lerning Rate 0.00030805409768163496


[274] train-loss: 0.29164913525948155


[275] train-loss: 0.2972509402495164


[276] train-loss: 0.2829719919424791


[276] validation-loss: 0.2612178163094954 Lerning Rate 0.0002655808538415357


[277] train-loss: 0.2882932103597201


[278] train-loss: 0.2814563191854037


[279] train-loss: 0.2919858464827904


[279] validation-loss: 0.26401940800926904 Lerning Rate 0.00022500000000000008


[280] train-loss: 0.3082723938501798


[281] train-loss: 0.2868053683867821


[282] train-loss: 0.2867582211127648


[282] validation-loss: 0.2602863203395497 Lerning Rate 0.0001867279506321116


[283] train-loss: 0.30642381539711583


[284] train-loss: 0.28461209627298206


[285] train-loss: 0.2949374547371498


[285] validation-loss: 0.24833854220130228 Lerning Rate 0.00015115742875474234


[286] train-loss: 0.31627442286564755


[287] train-loss: 0.2848939253733708


[288] train-loss: 0.2875528335571289


[288] validation-loss: 0.24687653238123114 Lerning Rate 0.00011865343605696116


[289] train-loss: 0.28112385823176456


[290] train-loss: 0.2806984002773578


[291] train-loss: 0.28177035313386184


[291] validation-loss: 0.2524741237813776 Lerning Rate 8.954950748877685e-05


[292] train-loss: 0.2785424773509686


[293] train-loss: 0.2786542452298678


[294] train-loss: 0.3222447175246019


[294] validation-loss: 0.24965945157137784 Lerning Rate 6.414428874120698e-05


[295] train-loss: 0.3251510170789865


[296] train-loss: 0.2896566161742577


[297] train-loss: 0.28329981290377104


[297] validation-loss: 0.24987887252460828 Lerning Rate 4.269847173735541e-05


[298] train-loss: 0.28746349536455595


[299] train-loss: 0.28011125784653884


[300] train-loss: 0.28352511387604934


[300] validation-loss: 0.25240504199808295 Lerning Rate 2.5432119580508876e-05


[301] train-loss: 0.306500269816472


[302] train-loss: 0.2839350700378418


[303] train-loss: 0.2860154142746559


[303] validation-loss: 0.2524645816196095 Lerning Rate 1.252240840890424e-05


[304] train-loss: 0.3012666152073787


[305] train-loss: 0.28084248762864333


[306] train-loss: 0.28483779155291045


[306] validation-loss: 0.2510438453067433 Lerning Rate 4.101809328792519e-06


[307] train-loss: 0.2901087999343872


[308] train-loss: 0.29894136924010056


[309] train-loss: 0.28191441756028396


[309] validation-loss: 0.2511053518815474 Lerning Rate 2.567290816268995e-07
DONE.


In [5]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [6]:
prediction

tensor([[8.1751e-09, 7.7866e-07, 9.1112e-08, 1.0000e+00, 1.1654e-09],
        [7.8917e-09, 7.9131e-07, 1.0044e-07, 1.0000e+00, 1.7672e-09],
        [2.6293e-07, 1.0000e+00, 5.9445e-11, 5.9596e-10, 8.3633e-08],
        [5.4529e-07, 5.5853e-08, 1.0000e+00, 2.9399e-08, 1.1039e-06],
        [2.1192e-08, 2.3380e-12, 1.0000e+00, 4.1937e-11, 5.7587e-11],
        [9.9927e-01, 1.3875e-04, 5.0521e-04, 7.6006e-05, 5.2926e-06],
        [9.2417e-09, 2.5784e-07, 7.7077e-08, 1.0000e+00, 3.5888e-10],
        [4.8748e-12, 1.0000e+00, 9.2828e-12, 9.4536e-10, 1.0514e-09],
        [1.1424e-08, 1.0000e+00, 2.1505e-10, 4.7224e-08, 8.8493e-09],
        [4.8963e-06, 3.7303e-07, 1.4507e-09, 7.5827e-11, 9.9999e-01],
        [8.9398e-06, 3.5119e-09, 9.9999e-01, 3.8491e-08, 2.3634e-08],
        [1.7540e-07, 5.6175e-10, 1.0000e+00, 4.0932e-10, 1.5227e-08],
        [1.0735e-06, 6.0700e-08, 1.9198e-06, 2.2887e-09, 1.0000e+00],
        [8.3475e-07, 1.5465e-08, 1.0000e+00, 2.0683e-08, 8.1588e-07],
        [9.9997e-01,

In [7]:
label

tensor([3, 3, 1, 2, 2, 0, 3, 1, 1, 4, 2, 2, 4, 2, 0, 1, 2, 3, 3, 1, 3],
       device='cuda:0')

In [8]:
all_labels = []
all_predictions = []

with torch.no_grad():
    for batch, labels in tqdm(zip(x_train_hist, y_train_hist)):
        for minibatch, label in zip(batch, labels):
            sample = minibatch.cuda()

            prediction = net(sample)
            all_predictions.append(prediction.cpu())
            
            all_labels.append(label)

In [9]:
all_predictions = [item.argmax().tolist() for sublist in all_predictions for item in sublist]
all_labels = [item.tolist() for sublist in all_labels for item in sublist]
print(classification_report(all_labels, all_predictions))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      6339
           1       1.00      0.96      0.98      6175
           2       0.99      0.99      0.99      6165
           3       1.00      1.00      1.00      6208
           4       0.96      0.99      0.98      6113

    accuracy                           0.99     31000
   macro avg       0.99      0.99      0.99     31000
weighted avg       0.99      0.99      0.99     31000



In [11]:
confusion_matrix(all_labels, all_predictions)

array([[6295,    1,   40,    0,    3],
       [ 185, 5806,   23,    0,  161],
       [   7,    0, 6158,    0,    0],
       [   0,    0,    0, 6208,    0],
       [  41,    7,   32,    0, 6033]], dtype=int64)

In [10]:
confusion_matrix(all_labels, all_predictions)

array([[6283,    3,   20,    0,   33],
       [  52, 5898,    9,    0,  216],
       [  40,    0, 6125,    0,    0],
       [   0,    0,    0, 6208,    0],
       [  28,    2,   13,    0, 6070]], dtype=int64)

In [11]:
all_labels = []
all_predictions = []

with torch.no_grad():
    for batch, labels in tqdm(zip(x_valid_hist, y_valid_hist)):
        for minibatch, label in zip(batch, labels):
            sample = minibatch.cuda()

            prediction = net(sample)
            all_predictions.append(prediction.cpu())
            
            all_labels.append(label)

In [12]:
all_predictions = [item.argmax().tolist() for sublist in all_predictions for item in sublist]
all_labels = [item.tolist() for sublist in all_labels for item in sublist]
print(classification_report(all_labels, all_predictions))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      2727
           1       0.99      0.96      0.97      2714
           2       0.99      1.00      0.99      2710
           3       1.00      1.00      1.00      2714
           4       0.98      0.98      0.98      2735

    accuracy                           0.99     13600
   macro avg       0.99      0.99      0.99     13600
weighted avg       0.99      0.99      0.99     13600



In [13]:
print(confusion_matrix(all_labels, all_predictions))

[[2717    0    6    0    4]
 [  45 2605    8    0   56]
 [   2    0 2707    0    1]
 [   0    0    0 2714    0]
 [  10   25   11    0 2689]]


In [10]:
torch.save({'epoch': epoch,
            'model_state_dict': net.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': validation_loss.item()}, 'final')

In [11]:
model = torch.load("checkpoint_best")

In [12]:
model = CatNet(num_classes=5)
optimizer = optim.Ranger(
    net.parameters(),
    lr=1e-3,
    alpha=0.5,
    k=6,
    N_sma_threshhold=5,
    betas=(.95, 0.999),
    eps=1e-5,
    weight_decay=0
)

checkpoint = torch.load("checkpoint_best")
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']

model.eval()
model.cuda()

CatNet(
  (block1): Sequential(
    (0): Conv2d(1, 82, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3))
    (1): BatchNorm2d(82, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): mish_layer()
  )
  (maxpool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (block2): skip_connection_block(
    (conv_il): Conv2d(82, 82, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (batn_il): BatchNorm2d(82, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv_ol): Conv2d(82, 82, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batn_ol): BatchNorm2d(82, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv_sl): Conv2d(82, 82, kernel_size=(1, 1), stride=(2, 2))
    (batn_sl): BatchNorm2d(82, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (block3): skip_connection_block(
    (conv_il): Conv2d(82, 82, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
    (batn_il): BatchNor

In [13]:
all_labels = []
all_predictions = []

with torch.no_grad():
    for batch, labels in tqdm(zip(x_valid_hist, y_valid_hist)):
        for minibatch, label in zip(batch, labels):
            sample = minibatch.cuda()

            prediction = model(sample)
            all_predictions.append(prediction.cpu())
            
            all_labels.append(label)

In [14]:
all_predictions = [item.argmax().tolist() for sublist in all_predictions for item in sublist]
all_labels = [item.tolist() for sublist in all_labels for item in sublist]
print(classification_report(all_labels, all_predictions))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2727
           1       1.00      0.97      0.98      2714
           2       0.99      1.00      0.99      2710
           3       1.00      1.00      1.00      2714
           4       0.98      1.00      0.99      2735

    accuracy                           0.99     13600
   macro avg       0.99      0.99      0.99     13600
weighted avg       0.99      0.99      0.99     13600



In [15]:
print(confusion_matrix(all_labels, all_predictions))

[[2698    3   16    0   10]
 [   8 2642   10    1   53]
 [   0    0 2708    0    2]
 [   0    0    0 2714    0]
 [   6    6    0    0 2723]]
